### ISSUE TITLE
Suppress word join (NoBreak) (U+2060)" could be added as a further option

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/ppcomp#17]
While the Unicode &NoBreak; character does what I want in a browser and, as far as I can see, in epub readers, there is a secondary issue with using it.

This is that PPCOMP treats it as a 'visible' or non-space character and hence flags it as a 'diff' in the HTML file.

That could be avoided if PPCOMP offered another option for transforming an HTML file. It already has the option to

    Suppress non-breakable spaces between numbers

and

    Suppress zero width space (U+200b)

Perhaps "Suppress word join (NoBreak) (U+2060)" could be added as a further option or its suppression in the comparison folded into one of the options above?

Quentin (QGC)

**Comment by G4OEU** [comment]
Here are the two files that I was comparing:
[aborigines-of-australia.txt](https://github.com/DistributedProofreaders/ppcomp/files/10039639/aborigines-of-australia.txt)
[aborigines-of-australia-HTML.txt](https://github.com/DistributedProofreaders/ppcomp/files/10039656/aborigines-of-australia-HTML.txt)

The second file should be named 'aborigines-of-australia.html' but GitHub does not support that file type for uploading.

**Comment by cpeel** [comment]
Fixed in #18
